name: revo_pos
description: A new Flutter project.

publish_to: "none"

version: 3.1.0+34

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.1
  dartz: ^0.10.1
  double_back_to_close: ^2.0.0
  equatable: ^2.0.3
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  fl_chart: ^0.50.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  html_unescape: ^2.0.0
  http: ^0.13.4
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6595
  money2: ^3.1.2
  multi_select_flutter: ^4.1.2
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9
  provider: ^6.0.2
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  syncfusion_flutter_datepicker: ^20.1.57
  url_launcher: ^6.0.20
  waterfall_flow: ^3.0.2
  timeago: ^3.2.2
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  change_app_package_name: ^1.1.0
  rxdart: ^0.27.4
  uni_links: ^0.5.1
  hexcolor: ^2.0.7
  flutter_local_notifications: ^9.6.1
  blue_thermal_printer: ^1.2.3
  flutter_native_splash: ^2.2.5
  flutter_widget_from_html: ^0.8.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  #color: "#42a5f5"
  background_image: "assets/images/splashscreen.png"
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.
  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  #image: assets/splash.png
  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false
  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center
  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
